name: Request a feature
description: Suggest a new feature for consideration
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: textarea
    id: new-feature
    validations:
      required: true