name: Request a feature
description: Request a feature
title: "Feature name:"
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        What do you think it would be cool to add*
  - type: textarea
    id: new-feature
    attributes:
      label: What happened?
      value: ""
    validations:
      required: true